const BUILD="20261008-4"; // legacy smoke marker: const BUILD="20261008-3"
const $=s=>document.querySelector(s),money=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(+n||0),num=n=>(+n||0).toFixed(2),esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const ep=o=>"/.netlify/functions/payroll-admin?op="+encodeURIComponent(o);let D={employees:[],entries:[],runs:[],audit:[]},QB={configured:false,connected:false},selectedEmployeeId="craig-wong",currentView="overview",payConfirmation=null,timer,CSV=null,CSVNAME="";
async function api(op,opt={}){const h={...(opt.headers||{})};if(opt.body)h["content-type"]="application/json";const url=ep(op)+(op==="status"||op==="me"?"&t="+Date.now():"");const r=await fetch(url,{credentials:"same-origin",cache:"no-store",...opt,headers:h}),j=await r.json().catch(()=>({error:"Request failed."}));if(r.status===401&&!["login","setup","status"].includes(op))login();if(!r.ok){const e=Error(j.error||"Request failed.");Object.assign(e,j);throw e}return j}
const employee=()=>D.employees.find(e=>e.id===selectedEmployeeId)||D.employees.find(e=>e.id==="craig-wong")||D.employees[0],
set=(id,v)=>{$(id).value=v??""},check=(id,v)=>{$(id).checked=!!v},date=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10),
employeeName=id=>D.employees.find(e=>e.id===id)?.name||"Unknown employee";
function employeeOptions(){const active=D.employees.filter(e=>e.status!=="Inactive"),html=active.map(e=>`<option value="${esc(e.id)}">${esc(e.name)}</option>`).join("");["#employee_select","#pay_employee_select"].forEach(id=>{const el=$(id);if(el){el.innerHTML=html;el.value=employee()?.id||""}})}
function showView(name){currentView=name;document.querySelectorAll("[data-admin-view]").forEach(el=>el.hidden=el.dataset.adminView!==name);document.querySelectorAll(".navTab").forEach(b=>b.classList.toggle("active",b.dataset.view===name));window.scrollTo({top:0,behavior:"smooth"})}
function chooseEmployee(id,view){if(!D.employees.some(e=>e.id===id))return;selectedEmployeeId=id;render();defaults(employee().pay_frequency,true);if(view)showView(view)}
function setup(){login()}function login(){const s=$("#setup");if(s)s.hidden=true;$("#login").hidden=false;$("#app").hidden=true}function app(){const s=$("#setup");if(s)s.hidden=true;$("#login").hidden=true;$("#app").hidden=false}
function completedWeek(){const t=new Date();t.setHours(12,0,0,0);const end=new Date(t);end.setDate(t.getDate()-(t.getDay()||7));const start=new Date(end);start.setDate(end.getDate()-6);return{start:date(start),end:date(end)}}
function defaults(freq,force=false){if(!force&&$("#period_start").value)return;const w=completedWeek(),z=new Date(w.end+"T12:00:00");const a=new Date(z);a.setDate(z.getDate()-(freq==="biweekly"?13:6));set("#period_start",date(a));set("#period_end",w.end);set("#payment_date",date(new Date()))}
function taxState(){const f=$("#w4_on_file").checked,h=$("#hw4_on_file").checked;["#federal_filing_status","#w4_step2_checked","#w4_step3_credits","#w4_step4a_other_income","#w4_step4b_deductions","#w4_step4c_extra","#w4_exempt","#w4_nonresident_alien","#w4_nra_india_exception"].forEach(x=>$(x).disabled=!f);["#hi_filing_status","#hi_allowances","#hi_additional_withholding"].forEach(x=>$(x).disabled=!h)}
function entryCovered(t){return D.runs.some(r=>r.employee_id===t.employee_id&&t.business_date>=r.period_start&&t.business_date<=r.period_end)}
function renderOverview(){
const active=D.employees.filter(e=>e.status!=="Inactive"),w=completedWeek(),weekEntries=D.entries.filter(t=>t.business_date>=w.start&&t.business_date<=w.end),hours=weekEntries.reduce((s,t)=>s+(+t.regular_hours||0)+(+t.overtime_hours||0),0),unpaidWeekEntries=weekEntries.filter(t=>!entryCovered(t)),awaiting=active.filter(e=>unpaidWeekEntries.some(t=>t.employee_id===e.id)),unpaidWeekHours=unpaidWeekEntries.reduce((s,t)=>s+(+t.regular_hours||0)+(+t.overtime_hours||0),0),unpaidWeekGross=unpaidWeekEntries.reduce((s,t)=>{const e=D.employees.find(x=>x.id===t.employee_id),rate=+t.hourly_wage||+e?.hourly_rate||0;return s+(+t.regular_hours||0)*rate+(+t.overtime_hours||0)*rate*1.5},0),last=[...D.runs].sort((a,b)=>String(b.payment_date).localeCompare(String(a.payment_date)))[0];
const outstanding=D.employees.map(e=>{const unpaidEntries=D.entries.filter(t=>t.employee_id===e.id&&t.business_date<=w.end&&!entryCovered(t)),unpaidHours=unpaidEntries.reduce((s,t)=>s+(+t.regular_hours||0)+(+t.overtime_hours||0),0),rateMissingHours=unpaidEntries.reduce((s,t)=>{const w=+t.hourly_wage||+e.hourly_rate||0;return s+(w>0?0:(+t.regular_hours||0)+(+t.overtime_hours||0))},0),unpaidGross=unpaidEntries.reduce((s,t)=>{const rate=+t.hourly_wage||+e.hourly_rate||0;return s+(+t.regular_hours||0)*rate+(+t.overtime_hours||0)*rate*1.5},0),runShortfall=D.runs.filter(r=>r.employee_id===e.id).reduce((s,r)=>s+Math.max(0,(+r.net_pay||0)-(+r.amount_paid||0)),0),owed=unpaidGross+runShortfall,oldest=unpaidEntries.map(t=>t.business_date).filter(Boolean).sort()[0]||"";return{employee:e,unpaidEntries,unpaidHours,rateMissingHours,unpaidGross,runShortfall,owed,oldest}}).filter(x=>x.owed>.004||x.unpaidHours>0);
const totalOwed=outstanding.reduce((s,x)=>s+x.owed,0),ratePendingHours=outstanding.reduce((s,x)=>s+x.rateMissingHours,0);
$("#overviewEmployeeCount").textContent=active.length;$("#overviewHours").textContent=num(hours);$("#overviewAwaiting").textContent=awaiting.length;$("#overviewOutstandingTotal").textContent=money(totalOwed)+(ratePendingHours>0?"*":"");$("#overviewOutstandingHero").textContent=money(totalOwed)+(ratePendingHours>0?"*":"");$("#overviewLastPayroll").textContent=last?last.payment_date:"—";$("#overviewPeriodLabel").textContent=`Completed pay week: ${w.start} – ${w.end}`;
const cards=active.map(e=>{const es=weekEntries.filter(t=>t.employee_id===e.id),eh=es.reduce((s,t)=>s+(+t.regular_hours||0)+(+t.overtime_hours||0),0),gross=es.reduce((s,t)=>s+(+t.regular_hours||0)*(+t.hourly_wage||+e.hourly_rate)+(+(t.overtime_hours)||0)*(+t.hourly_wage||+e.hourly_rate)*1.5,0),unpaidEntries=es.filter(t=>!entryCovered(t)),unpaid=unpaidEntries.length>0,status=!+e.hourly_rate?"Needs hourly rate":!eh?"No hours this week":unpaid?"Ready for payroll":"Payroll recorded";return `<article class="employeeCard"><div><p class="eyebrow">${esc(status)}</p><h3>${esc(e.name)}</h3><p>${money(e.hourly_rate)}/hr · ${num(eh)} hrs · ${money(gross)} gross</p></div><div class="actions"><button class="small secondary" data-open-employee="${esc(e.id)}">Employee</button><button class="small" data-run-payroll="${esc(e.id)}" ${unpaid?"":"disabled"}>${unpaid?"Payroll":"Paid"}</button></div></article>`}).join("");
$("#overviewEmployees").innerHTML=cards||'<p class="note">No active employees yet.</p>';
$("#overviewOutstandingEmployees").innerHTML=outstanding.length?outstanding.sort((a,b)=>b.owed-a.owed).map(x=>{const e=x.employee,parts=[];if(x.unpaidHours>0)parts.push(num(x.unpaidHours)+" unpaid hrs");if(x.runShortfall>.004)parts.push(money(x.runShortfall)+" remaining from recorded pay");if(x.rateMissingHours>0)parts.push(num(x.rateMissingHours)+" hrs need a rate");const sub=x.oldest?"Oldest unpaid shift: "+x.oldest:"Recorded payroll balance";return `<article class="outstandingRow"><div><h3>${esc(e.name)}</h3><p>${esc(parts.join(" · "))}</p><small>${esc(sub)}</small></div><div class="outstandingRight"><b>${money(x.owed)}${x.rateMissingHours>0?"*":""}</b><button class="small" data-run-payroll="${esc(e.id)}">${x.unpaidHours>0?"Run payroll":"Open payroll"}</button></div></article>`}).join(""):'<div class="allPaid"><b>All caught up</b><span>No unpaid employee wages are currently recorded.</span></div>';
$("#overviewOutstandingNote").textContent=ratePendingHours>0?"* Total through "+w.end+" excludes "+num(ratePendingHours)+" unpaid hour"+(ratePendingHours===1?"":"s")+" with no hourly rate configured yet.":"Amounts include unpaid wages through "+w.end+" plus any remaining balance from an underpaid recorded pay run.";
$("#overviewPayrollSummary").innerHTML=`<b>${awaiting.length} employee${awaiting.length===1?"":"s"} awaiting payroll</b><span>${num(unpaidWeekHours)} unpaid hours · ${money(unpaidWeekGross)} unpaid gross</span><span>${w.start} – ${w.end}</span>`;
const latest=[...D.entries].sort((a,b)=>String(b.synced_at||b.business_date).localeCompare(String(a.synced_at||a.business_date)))[0];
$("#overviewImportSummary").innerHTML=`<b>${D.entries.length} stored time entries</b><span>${latest?"Latest: "+esc(latest.business_date)+" · "+esc(employeeName(latest.employee_id)):"No time imported yet"}</span><span>Toast CSV preview protects against accidental imports.</span>`}
function render(){const e=employee();if(!e)return;selectedEmployeeId=e.id;employeeOptions();$("#employeeHeading").textContent=e.name;$("#payResult").textContent=payConfirmation?.employee_id===e.id?payConfirmation.message:"";["hourly_rate","pay_frequency","toast_employee_guid","federal_filing_status","w4_step3_credits","w4_step4a_other_income","w4_step4b_deductions","w4_step4c_extra","hi_filing_status","hi_allowances","hi_additional_withholding"].forEach(k=>set("#"+k,e[k]));["w4_on_file","w4_step2_checked","w4_exempt","w4_nonresident_alien","w4_nra_india_exception","hw4_on_file"].forEach(k=>check("#"+k,e[k]));defaults(e.pay_frequency);
const runs=D.runs.filter(r=>r.employee_id===e.id);
$("#runsBody").innerHTML=runs.map(r=>{const ded=+r.social_security+ +r.medicare+ +(r.additional_medicare||0)+ +r.federal_income_tax+ +r.hawaii_income_tax+ +r.other_deductions;return `<tr><td>${esc(r.payment_date)}</td><td>${esc(r.period_start)}–${esc(r.period_end)}</td><td>${esc(r.pay_frequency)}</td><td>${num(+r.regular_hours+ +r.overtime_hours)}</td><td>${money(r.gross_pay)}</td><td>${money(ded)}</td><td><b>${money(r.net_pay)}</b></td><td><b>${money(r.amount_paid)}</b></td><td>${esc(r.payment_method)}</td><td>${r.apply_tax_deductions?"Applied":"OFF"}</td></tr>`}).join("")||'<tr><td colspan="10">No payments recorded for this employee.</td></tr>';
$("#entriesBody").innerHTML=D.entries.map(t=>`<tr><td><b>${esc(employeeName(t.employee_id))}</b></td><td>${esc(t.business_date)}</td><td>${num(t.regular_hours)}</td><td>${num(t.overtime_hours)}</td><td>${money(t.hourly_wage)}</td><td>${money(+t.regular_hours*+t.hourly_wage+ +t.overtime_hours*+t.hourly_wage*1.5)}</td><td>${esc(t.source)}</td><td><button class="small secondary" data-a="edit" data-g="${esc(t.toast_guid)}">Edit</button> <button class="small danger" data-a="delete" data-g="${esc(t.toast_guid)}">Delete</button></td></tr>`).join("")||'<tr><td colspan="8">No time entries yet.</td></tr>';
$("#auditBody").innerHTML=(D.audit||[]).map(a=>{const b=a.before_data||{},n=a.after_data||{},x=n.employee_id||b.employee_id,d=n.business_date||b.business_date||"—";return `<tr><td><b>${esc(employeeName(x))}</b></td><td>${new Date(a.created_at).toLocaleString()}</td><td>${esc(a.action)}</td><td>${esc(d)}</td><td>${a.action==="delete"?"Deleted entry":`Changed ${num(b.regular_hours)} regular/${num(b.overtime_hours)} OT → ${num(n.regular_hours)} regular/${num(n.overtime_hours)} OT`}</td></tr>`}).join("")||'<tr><td colspan="5">No corrections recorded.</td></tr>';
const w=completedWeek(),ee=D.entries.filter(t=>t.employee_id===e.id&&t.business_date>=w.start&&t.business_date<=w.end),eh=ee.reduce((s,t)=>s+(+t.regular_hours||0)+(+t.overtime_hours||0),0),unpaid=ee.some(t=>!entryCovered(t));$("#payrollEmployeeStatus").innerHTML=`<b>${esc(e.name)}</b><span>${money(e.hourly_rate)}/hr · ${num(eh)} hours in completed week</span><span>${unpaid?"Ready for payroll":eh?"Completed-week hours already covered by a payroll run":"No completed-week hours yet"}</span>`;
renderOverview();taxState();previewSoon();showView(currentView)}
function renderQuickBooks(){const badge=$("#quickbooksBadge"),details=$("#quickbooksDetails"),connect=$("#quickbooksConnectBtn"),map=$("#quickbooksMapBtn"),disconnect=$("#quickbooksDisconnectBtn"),setup=$("#quickbooksSetupHelp"),payBtn=$("#quickbooksPayrollBtn"),heading=$("#qbPayrollHeading"),note=$("#qbPayrollNote");if($("#quickbooksRedirectUri"))$("#quickbooksRedirectUri").textContent=QB.redirect_uri||"https://koaslounge.com/.netlify/functions/payroll-admin?op=quickbooks-callback";setup.hidden=!!QB.configured;if(!QB.configured){badge.textContent="Setup required";badge.className="integrationBadge warning";details.innerHTML="<b>Not configured</b><span>Add the Intuit production client ID and secret to the Koa's server environment.</span>";connect.hidden=false;connect.disabled=true;map.hidden=true;disconnect.hidden=true;payBtn.disabled=true;heading.textContent="QuickBooks setup required";note.textContent="Finish the one-time Intuit developer setup in Settings before using direct deposit.";return}connect.disabled=false;if(QB.connected){badge.textContent="Connected";badge.className="integrationBadge connected";details.innerHTML=`<b>${esc(QB.company_name||"QuickBooks company")}</b><span>${QB.mapped_employees||0} of ${QB.total_employees||0} Koa's employees matched to QuickBooks</span><span>Final payroll approval and direct deposit stay inside QuickBooks.</span>`;connect.hidden=true;map.hidden=false;disconnect.hidden=false;payBtn.disabled=false;heading.textContent="Continue with QuickBooks";note.textContent="Sync this employee's pay-period hours, then review overtime, taxes, funding account and direct deposit in QuickBooks Payroll."}else{badge.textContent="Not connected";badge.className="integrationBadge";details.innerHTML=`<b>Ready to connect</b><span>${esc(QB.error||"Authorize Koa's Admin to access your QuickBooks accounting company.")}</span>`;connect.hidden=false;map.hidden=true;disconnect.hidden=true;payBtn.disabled=true;heading.textContent="QuickBooks not connected";note.textContent="Connect QuickBooks in Settings to sync this pay period and continue into QuickBooks Payroll."}}
async function refreshQuickBooks(){try{QB=await api("quickbooks-status");renderQuickBooks()}catch(x){QB={configured:false,connected:false,error:x.message};renderQuickBooks()}}

async function load(){const [data,qb]=await Promise.all([api("data"),api("quickbooks-status").catch(()=>({configured:false,connected:false}))]);D=data;QB=qb;if(!D.employees.some(e=>e.id===selectedEmployeeId))selectedEmployeeId=D.employees[0]?.id||"";render();renderQuickBooks()}
function emp(){const e=employee(),o={id:e.id};["hourly_rate","pay_frequency","toast_employee_guid","federal_filing_status","w4_step3_credits","w4_step4a_other_income","w4_step4b_deductions","w4_step4c_extra","hi_filing_status","hi_allowances","hi_additional_withholding"].forEach(k=>o[k]=$("#"+k).value);["w4_on_file","w4_step2_checked","w4_exempt","w4_nonresident_alien","w4_nra_india_exception","hw4_on_file"].forEach(k=>o[k]=$("#"+k).checked);return o}
const pay=()=>({employee_id:employee().id,period_start:$("#period_start").value,period_end:$("#period_end").value,payment_date:$("#payment_date").value,apply_tax_deductions:$("#apply_tax_deductions").checked,other_deductions:$("#other_deductions").value,amount_paid:$("#amount_paid").value,payment_method:$("#payment_method").value,payment_reference:$("#payment_reference").value,notes:$("#notes").value});
async function preview(){if(!employee()||!$("#period_start").value)return;try{const r=await api("pay-preview",{method:"POST",body:JSON.stringify(pay())});$("#pvHours").textContent=num(+r.regular_hours+ +r.overtime_hours);$("#pvGross").textContent=money(r.gross_pay);$("#pvFederal").textContent=money(r.federal_income_tax);$("#pvHawaii").textContent=money(r.hawaii_income_tax);$("#pvFica").textContent=money(+r.social_security+ +r.medicare+ +(r.additional_medicare||0));$("#pvNet").textContent=money(r.net_pay)}catch{}}function previewSoon(){clearTimeout(timer);timer=setTimeout(preview,200)}
function status(msg,type="success"){const e=$("#importStatus");e.hidden=false;e.className="status "+type;e.textContent=msg}
const setupForm=$("#setupForm");if(setupForm)setupForm.onsubmit=async e=>{e.preventDefault();login()};
$("#loginForm").onsubmit=async e=>{e.preventDefault();const b=$("#loginSubmit");$("#loginMsg").className="status working";$("#loginMsg").textContent="Signing in…";b.disabled=true;b.classList.add("is-loading");b.textContent="Signing in…";try{await api("login",{method:"POST",body:JSON.stringify({email:$("#email").value,password:$("#password").value})});$("#loginMsg").className="status working";$("#loginMsg").textContent="Password accepted. Establishing secure session…";await new Promise(r=>setTimeout(r,150));try{await api("me");$("#loginMsg").className="ok";$("#loginMsg").textContent="Signed in.";currentView="overview";app();await load()}catch(s){login();$("#loginMsg").className="error";$("#loginMsg").textContent="Password accepted, but the secure session did not persist. Please send a screenshot of this message."}}catch(x){$("#loginMsg").className="error";$("#loginMsg").textContent=x.message||"Sign-in failed."}finally{b.disabled=false;b.classList.remove("is-loading");b.textContent="Sign in"}};$("#showRecovery").onclick=()=>{$("#recoveryPanel").hidden=!$("#recoveryPanel").hidden};
$("#recoveryForm").onsubmit=async e=>{e.preventDefault();$("#recoveryMsg").className="error";$("#recoveryMsg").textContent="";if($("#recovery_password").value!==$("#recovery_confirm").value){$("#recoveryMsg").textContent="Passwords do not match.";return}try{const r=await api("admin-recovery",{method:"POST",body:JSON.stringify({email:$("#recovery_email").value,recovery_key:$("#recovery_key").value,new_password:$("#recovery_password").value})});$("#recoveryMsg").className="ok";$("#recoveryMsg").textContent=r.message||"Password reset complete.";$("#email").value=$("#recovery_email").value;$("#password").value="";$("#recovery_password").value=$("#recovery_confirm").value=$("#recovery_key").value="";}catch(x){$("#recoveryMsg").textContent=x.message}};$("#logout").onclick=async()=>{await api("logout",{method:"POST"}).catch(()=>{});login()};
const openAddEmployee=()=>{$("#addEmployeeMsg").textContent="";$("#new_employee_name").value="";$("#new_employee_rate").value="";$("#new_employee_frequency").value="weekly";$("#new_employee_toast_alias").value="";$("#addEmployeeDialog").showModal()};$("#addEmployeeBtn").onclick=openAddEmployee;$("#overviewAddEmployeeBtn").onclick=openAddEmployee;
const closeAddEmployee=()=>$("#addEmployeeDialog").close();
$("#addEmployeeCancel").onclick=closeAddEmployee;$("#addEmployeeClose").onclick=closeAddEmployee;
$("#addEmployeeForm").onsubmit=async e=>{e.preventDefault();$("#addEmployeeMsg").textContent="";try{const r=await api("employee-create",{method:"POST",body:JSON.stringify({name:$("#new_employee_name").value,hourly_rate:$("#new_employee_rate").value,pay_frequency:$("#new_employee_frequency").value,toast_alias:$("#new_employee_toast_alias").value})});closeAddEmployee();await load();chooseEmployee(r.employee.id,"employees");status("Employee created: "+r.employee.name+(+r.employee.hourly_rate>0?" · "+money(r.employee.hourly_rate)+"/hr":" · hourly rate needs setup."));}catch(x){$("#addEmployeeMsg").textContent=x.message}};
$("#quickbooksConnectBtn").onclick=async()=>{try{$("#quickbooksMsg").textContent="Preparing QuickBooks connection…";const r=await api("quickbooks-connect",{method:"POST",body:"{}"});location.href=r.authorization_url}catch(x){$("#quickbooksMsg").textContent=x.message}};
$("#quickbooksDisconnectBtn").onclick=async()=>{if(!confirm("Disconnect QuickBooks from Koa's Admin?"))return;try{await api("quickbooks-disconnect",{method:"POST",body:"{}"});$("#quickbooksMsg").textContent="QuickBooks disconnected.";await refreshQuickBooks()}catch(x){$("#quickbooksMsg").textContent=x.message}};
$("#quickbooksMapBtn").onclick=async()=>{try{$("#quickbooksMsg").textContent="Matching employees by name…";const r=await api("quickbooks-map-employees",{method:"POST",body:"{}"});$("#quickbooksMsg").textContent="Matched "+r.mapped+" employee"+(r.mapped===1?"":"s")+(r.unmatched?.length?". Not matched: "+r.unmatched.join(", ")+".":".");await load()}catch(x){$("#quickbooksMsg").textContent=x.message}};
$("#quickbooksPayrollBtn").onclick=async()=>{const w=window.open("about:blank","_blank");$("#quickbooksPayrollMsg").textContent="Syncing this pay period to QuickBooks…";try{const r=await api("quickbooks-sync-time",{method:"POST",body:JSON.stringify({employee_id:employee().id,period_start:$("#period_start").value,period_end:$("#period_end").value})});$("#quickbooksPayrollMsg").textContent="Synced "+r.synced+" new time entr"+(r.synced===1?"y":"ies")+" ("+num(r.total_hours)+" hrs). "+r.warning;if(w)w.location=r.open_url;else location.href=r.open_url;await load()}catch(x){if(w)w.close();$("#quickbooksPayrollMsg").textContent=x.message}};
document.querySelectorAll(".navTab").forEach(b=>b.onclick=()=>showView(b.dataset.view));
$("#dashboardImportBtn").onclick=()=>$("#csvFile").click();
$("#overviewImportBtn").onclick=()=>$("#csvFile").click();
$("#importsImportBtn").onclick=()=>$("#csvFile").click();
$("#dashboardPayrollBtn").onclick=()=>showView("payroll");
$("#overviewPayrollBtn").onclick=()=>showView("payroll");
$("#overviewEmployeesBtn").onclick=()=>showView("employees");
$("#overviewTimeBtn").onclick=()=>showView("time");
const overviewEmployeeAction=e=>{const a=e.target.closest("[data-open-employee]"),p=e.target.closest("[data-run-payroll]");if(a)chooseEmployee(a.dataset.openEmployee,"employees");if(p)chooseEmployee(p.dataset.runPayroll,"payroll")};$("#overviewEmployees").onclick=overviewEmployeeAction;$("#overviewOutstandingEmployees").onclick=overviewEmployeeAction;
$("#employee_select").onchange=e=>chooseEmployee(e.target.value);$("#pay_employee_select").onchange=e=>chooseEmployee(e.target.value);
$("#employeeForm").onsubmit=async e=>{e.preventDefault();const r=await api("employee",{method:"POST",body:JSON.stringify({employee:emp()})});$("#employeeSaved").textContent=r.rate_backfilled?"Saved. Applied this rate to "+r.rate_backfilled+" previously rate-less imported shift"+(r.rate_backfilled===1?"":"s")+".":"Saved.";await load()};$("#pay_frequency").onchange=()=>defaults($("#pay_frequency").value,true);["#w4_on_file","#hw4_on_file"].forEach(x=>$(x).onchange=()=>{taxState();previewSoon()});["#period_start","#period_end","#payment_date","#other_deductions","#apply_tax_deductions"].forEach(x=>$(x).oninput=previewSoon);
$("#payForm").onsubmit=async e=>{e.preventDefault();const selected=employee(),r=await api("pay-create",{method:"POST",body:JSON.stringify(pay())}),paidEmployee=D.employees.find(x=>x.id===r.employee_id)||selected;payConfirmation={employee_id:r.employee_id,message:"Recorded "+money(r.amount_paid)+" paid to "+paidEmployee.name+" via "+r.payment_method+"."};$("#amount_paid").value="";await load()};
$("#syncBtn").onclick=async()=>{const z=new Date(),a=new Date(z);a.setDate(a.getDate()-29);try{status("Syncing Toast…","working");const r=await api("toast-sync",{method:"POST",body:JSON.stringify({start:date(a),end:date(z)})});status("Toast sync complete: "+r.imported+" imported, "+r.skipped+" skipped.");await load()}catch(x){status(x.message,"error")}};
$("#passwordForm").onsubmit=async e=>{e.preventDefault();try{await api("change-password",{method:"POST",body:JSON.stringify({current_password:$("#current_password").value,new_password:$("#new_password").value})});$("#passwordMsg").textContent="Password changed.";$("#current_password").value=$("#new_password").value=""}catch(x){$("#passwordMsg").textContent=x.message}};
function parse(text){const rows=[];let r=[],f="",q=false;for(let i=0;i<text.length;i++){const c=text[i];if(q){if(c==='"'){if(text[i+1]==='"'){f+='"';i++}else q=false}else f+=c}else if(c==='"')q=true;else if(c===","){r.push(f);f=""}else if(c==="\n"){r.push(f.replace(/\r$/,""));if(r.some(x=>x.trim()))rows.push(r);r=[];f=""}else f+=c}r.push(f);if(r.some(x=>x.trim()))rows.push(r);return rows}
const key=s=>s.toLowerCase().replace(/^\ufeff/,"").replace(/[^a-z0-9]/g,""),aliases={
name:["employeename","employee","name"],
date:["businessdate","date","shiftdate","workdate"],
reg:["regularhours","reghours","regular"],
ot:["overtimehours","othours","overtime"],
payable:["payablehours","payablehrs"],
total:["totalhours","hours","workedhours"],
rate:["hourlywage","hourlyrate","payrate","wage","rate"],
guid:["timeentryguid","toastguid","timeentryid"],
tin:["timein","clockin","clockintime","indate"],
tout:["timeout","clockout","clockouttime","outdate"],
unpaid:["unpaidbreaktime","unpaidbreak"],
paid:["paidbreaktime","paidbreak"],
tips:["cashtipsdeclared","declaredcashtips"]
},first=(o,a)=>a.map(k=>o[k]).find(v=>String(v||"").trim())||"",n=v=>+String(v||"0").replace(/[$,%\s]/g,"")||0;
const MONTHS={jan:"01",feb:"02",mar:"03",apr:"04",may:"05",jun:"06",jul:"07",aug:"08",sep:"09",oct:"10",nov:"11",dec:"12"};
function iso(v){v=String(v||"").trim();if(/^\d{8}$/.test(v))return v.slice(0,4)+"-"+v.slice(4,6)+"-"+v.slice(6,8);if(/^\d{4}-\d{2}-\d{2}$/.test(v))return v;let m=/^(\d{1,2})-([A-Za-z]{3})-(\d{2}|\d{4})$/.exec(v);if(m){let y=+m[3];if(y<100)y+=2000;const mo=MONTHS[m[2].toLowerCase()];if(mo)return String(y).padStart(4,"0")+"-"+mo+"-"+String(+m[1]).padStart(2,"0")}m=/^([A-Za-z]{3})\s+(\d{1,2}),\s*(\d{4})$/.exec(v);if(m){const mo=MONTHS[m[1].toLowerCase()];if(mo)return m[3]+"-"+mo+"-"+String(+m[2]).padStart(2,"0")}const d=new Date(v);return Number.isNaN(d.getTime())?"":date(d)}
function clock(v){const m=/^(\d{1,2}):(\d{2})\s*(AM|PM)$/i.exec(String(v||"").trim());if(!m)return null;let h=+m[1]%12;if(m[3].toUpperCase()==="PM")h+=12;return h*60+(+m[2])}
function addDaysIso(d,days){const z=new Date(d+"T12:00:00Z");z.setUTCDate(z.getUTCDate()+days);return z.toISOString().slice(0,10)}
function stamp(d,v,next=false){const mins=clock(v);if(!d||mins==null)return null;const dd=next?addDaysIso(d,1):d,hh=String(Math.floor(mins/60)).padStart(2,"0"),mm=String(mins%60).padStart(2,"0");return dd+"T"+hh+":"+mm+":00-10:00"}
function weekMonday(d){const z=new Date(d+"T12:00:00Z"),delta=(z.getUTCDay()+6)%7;z.setUTCDate(z.getUTCDate()-delta);return z.toISOString().slice(0,10)}
function nameParts(v){v=String(v||"").trim();if(v.includes(",")){const a=v.split(","),last=(a.shift()||"").trim(),first=a.join(" ").trim();return{first,last}}const p=v.split(/\s+/).filter(Boolean);return{first:p.slice(0,-1).join(" "),last:p.at(-1)||""}}
const cleanName=v=>String(v||"").toLowerCase().replace(/[^a-z0-9]/g,""),toastDisplayName=v=>{const p=nameParts(v);return [p.first,p.last].filter(Boolean).join(" ")||String(v||"").trim()};
function findEmployeeForToast(nm){if(!nm)return employee();const target=cleanName(nm),parts=nameParts(nm),active=D.employees.filter(e=>e.status!=="Inactive");let m=active.find(e=>(e.toast_aliases||[]).some(a=>cleanName(a)===target));if(m)return m;m=active.find(e=>cleanName(e.name)===target);if(m)return m;const last=cleanName(parts.last),sameLast=active.filter(e=>cleanName(nameParts(e.name).last)===last);return sameLast.length===1?sameLast[0]:null}
function csvShiftKey(r){const who=r.employee_id||("toast:"+cleanName(r.toast_employee_name||r.employee_name)),d=String(r.business_date||""),tin=String(r.in_date||""),tout=String(r.out_date||"");return who&&d&&tin&&tout?JSON.stringify([who,d,tin,tout]):""}
function markCsvDuplicates(rows){const seen=new Set(D.entries.filter(t=>t.source==="Toast CSV").map(t=>csvShiftKey(t)).filter(Boolean));for(const r of rows){const k=csvShiftKey(r);if(!k)continue;if(seen.has(k)){r.duplicate=true;validateCsvRow(r)}else seen.add(k)}}
function allocateWeeklyOt(rows){const groups={};for(const r of rows){if(!r.valid||r.overtime_mode!=="weekly-derived"||!r.business_date)continue;const who=r.employee_id||"new:"+cleanName(r.toast_employee_name);(groups[who+"|"+weekMonday(r.business_date)]||=[]).push(r)}for(const arr of Object.values(groups)){arr.sort((a,b)=>a.business_date.localeCompare(b.business_date)||String(a.in_date||"").localeCompare(String(b.in_date||"")));let used=0;for(const r of arr){const total=Math.max(0,+r.total_hours||0),reg=Math.min(total,Math.max(0,40-used));r.regular_hours=Math.round(reg*100)/100;r.overtime_hours=Math.round((total-reg)*100)/100;used+=total}}}
function validateCsvRow(r){const worked=Math.max(0,+r.total_hours||(+r.regular_hours||0)+(+r.overtime_hours||0));r.valid=!!(r.business_date&&worked>0&&!r.duplicate);r.error=r.duplicate?"Already imported — duplicate shift.":r.valid?"":!r.business_date?"Invalid Toast date.":worked<=0?"No payable hours.":"Check this row."}
async function csv(file){const t=parse(await file.text());if(!t.length)throw Error("CSV is empty.");const hs=t.shift().map(key),out=[],hasReg=aliases.reg.some(h=>hs.includes(h)),hasOt=aliases.ot.some(h=>hs.includes(h)),deriveOt=!hasReg&&!hasOt;for(let i=0;i<t.length;i++){const o=Object.fromEntries(hs.map((h,j)=>[h,t[i][j]||""])),nm=first(o,aliases.name),match=findEmployeeForToast(nm),d=iso(first(o,aliases.date)),payable=Math.max(0,n(first(o,aliases.payable))),reportedTotal=Math.max(0,n(first(o,aliases.total))),total=Math.max(0,payable||reportedTotal),ot=hasOt?Math.max(0,n(first(o,aliases.ot))):0,reg=hasReg?Math.max(0,n(first(o,aliases.reg))):Math.max(0,total-ot),w=Math.max(0,n(first(o,aliases.rate))||+match?.hourly_rate||0),tin=first(o,aliases.tin),tout=first(o,aliases.tout),im=clock(tin),om=clock(tout),row={row_number:i+2,employee_id:match?.id||null,employee_name:match?.name||toastDisplayName(nm),toast_employee_name:nm||match?.name||"",new_employee:!match,business_date:d,regular_hours:deriveOt?total:reg,overtime_hours:deriveOt?0:ot,total_hours:deriveOt?total:reg+ot,hourly_wage:w,in_date:stamp(d,tin),out_date:stamp(d,tout,im!=null&&om!=null&&om<=im),provided_guid:first(o,aliases.guid),overtime_mode:deriveOt?"weekly-derived":"toast-explicit",raw:o};validateCsvRow(row);out.push(row)}allocateWeeklyOt(out);markCsvDuplicates(out);return out}
function csvView(rows,name){const v=rows.filter(x=>x.valid),dups=rows.filter(x=>x.duplicate).length,bad=rows.length-v.length-dups,derived=rows.some(x=>x.overtime_mode==="weekly-derived"),newNames=[...new Set(rows.filter(x=>x.new_employee&&(+x.total_hours||0)>0).map(x=>x.toast_employee_name))];$("#csvPreviewFile").textContent=name+" · "+rows.length+" rows"+(derived?" · OT derived from Payable Hours by Monday–Sunday week":"");const box=$("#csvNewEmployees");box.hidden=!newNames.length;box.innerHTML=newNames.length?'<h3>New employees detected</h3><p class="note">These employees will be added automatically when you approve the import. Their time entries will import now even if Toast does not provide an hourly rate. Set the rate later from Employees before running payroll.</p>'+newNames.map(nm=>{const r=rows.find(x=>x.toast_employee_name===nm);return `<div class="newEmployeeDetected"><b>${esc(toastDisplayName(nm))}</b><span>Toast: ${esc(nm)}</span><span>${+r?.hourly_wage>0?money(r.hourly_wage)+"/hr":"Rate needs setup"}</span></div>`}).join(""):"";$("#csvSummary").innerHTML=`<div><small>New rows</small><b>${v.length}</b></div><div><small>Duplicates</small><b>${dups}</b></div><div><small>Issues</small><b>${bad}</b></div><div><small>Hours</small><b>${num(v.reduce((s,x)=>s+x.regular_hours+x.overtime_hours,0))}</b></div>`;$("#csvPreviewBody").innerHTML=rows.map(x=>{const mapped=x.toast_employee_name&&x.toast_employee_name!==x.employee_name?`<small class="csvMap">Toast: ${esc(x.toast_employee_name)} → ${esc(x.employee_name)}</small>`:"",state=x.valid?(x.new_employee?(+x.hourly_wage>0?"Ready · new employee":"Ready · new employee · rate later"):x.overtime_mode==="weekly-derived"?"Ready · weekly OT":"Ready"):esc(x.error);return `<tr class="${x.valid?"":"bad"}"><td>${x.row_number}</td><td>${esc(x.employee_name)}${mapped}</td><td>${esc(x.business_date)}</td><td>${num(x.regular_hours)}</td><td>${num(x.overtime_hours)}</td><td>${x.hourly_wage?money(x.hourly_wage):"Rate later"}</td><td>${state}</td></tr>`}).join("");$("#csvApprove").disabled=!v.length}
$("#csvFile").onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{CSV=await csv(f);CSVNAME=f.name;csvView(CSV,f.name);$("#csvDialog").showModal();status("Preview ready. Nothing imported yet.","working")}catch(x){status(x.message,"error")}};const closeCsv=()=>{$("#csvDialog").close();$("#csvFile").value="";CSV=null};$("#csvCancel").onclick=closeCsv;$("#csvClose").onclick=closeCsv;$("#csvApprove").onclick=async()=>{const r=await api("csv-import",{method:"POST",body:JSON.stringify({file:CSVNAME,rows:CSV.filter(x=>x.valid)})});const made=(r.created_employees||[]).map(e=>e.name);status("CSV import complete: "+r.imported+" new, "+(r.updated||0)+" updated, "+(r.duplicates_skipped||0)+" duplicate"+((r.duplicates_skipped||0)===1?"":"s")+" skipped, "+r.skipped+" other skipped."+(made.length?" Created employee"+(made.length>1?"s":"")+": "+made.join(", ")+".":""));closeCsv();await load();showView("overview");if(made.length){const created=D.employees.find(e=>e.name===made[0]);if(created)selectedEmployeeId=created.id;renderOverview()}};
function edit(t){set("#edit_guid",t.toast_guid);set("#edit_business_date",t.business_date);set("#edit_regular_hours",t.regular_hours);set("#edit_overtime_hours",t.overtime_hours);set("#edit_hourly_wage",t.hourly_wage);$("#editDialog").showModal()}const editBody=c=>({toast_guid:$("#edit_guid").value,business_date:$("#edit_business_date").value,regular_hours:$("#edit_regular_hours").value,overtime_hours:$("#edit_overtime_hours").value,hourly_wage:$("#edit_hourly_wage").value,confirm_paid_period:c});
$("#editForm").onsubmit=async e=>{e.preventDefault();try{await api("time-update",{method:"POST",body:JSON.stringify(editBody(false))})}catch(x){if(!x.requires_confirmation||!confirm("This shift is in a recorded payroll period. Historical payroll will remain unchanged. Continue?"))return;await api("time-update",{method:"POST",body:JSON.stringify(editBody(true))})}$("#editDialog").close();await load()};$("#editCancel").onclick=()=>$("#editDialog").close();$("#entriesBody").onclick=async e=>{const b=e.target.closest("button[data-a]");if(!b)return;const t=D.entries.find(x=>x.toast_guid===b.dataset.g);if(b.dataset.a==="edit")return edit(t);if(!confirm("Delete this time entry? An audit record will remain."))return;try{await api("time-delete",{method:"POST",body:JSON.stringify({toast_guid:t.toast_guid})})}catch(x){if(!x.requires_confirmation||!confirm("This shift is in a recorded payroll period. Historical payroll will remain unchanged. Delete anyway?"))return;await api("time-delete",{method:"POST",body:JSON.stringify({toast_guid:t.toast_guid,confirm_paid_period:true})})}await load()};
(async()=>{try{await api("me");app();await load();const qs=new URLSearchParams(location.search),qb=qs.get("quickbooks");if(qb){showView("settings");$("#quickbooksMsg").textContent=qb==="connected"?"QuickBooks connected successfully.":"QuickBooks connection failed. Please verify the Intuit app settings and try again.";history.replaceState(null,"",location.pathname)}}catch{login()}})();