const BUILD="20261007-4"; // legacy smoke marker: const BUILD="20261007-3"
const $=s=>document.querySelector(s),money=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(+n||0),num=n=>(+n||0).toFixed(2),esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const ep=o=>"/.netlify/functions/payroll-admin?op="+encodeURIComponent(o);let D={employees:[],entries:[],runs:[],audit:[]},selectedEmployeeId="craig-wong",currentView="overview",timer,CSV=null,CSVNAME="";
async function api(op,opt={}){const h={...(opt.headers||{})};if(opt.body)h["content-type"]="application/json";const url=ep(op)+(op==="status"||op==="me"?"&t="+Date.now():"");const r=await fetch(url,{credentials:"same-origin",cache:"no-store",...opt,headers:h}),j=await r.json().catch(()=>({error:"Request failed."}));if(r.status===401&&!["login","setup","status"].includes(op))login();if(!r.ok){const e=Error(j.error||"Request failed.");Object.assign(e,j);throw e}return j}
const employee=()=>D.employees.find(e=>e.id===selectedEmployeeId)||D.employees.find(e=>e.id==="craig-wong")||D.employees[0],
set=(id,v)=>{$(id).value=v??""},check=(id,v)=>{$(id).checked=!!v},date=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10),
employeeName=id=>D.employees.find(e=>e.id===id)?.name||"Unknown employee";
function employeeOptions(){const active=D.employees.filter(e=>e.status!=="Inactive"),html=active.map(e=>`<option value="${esc(e.id)}">${esc(e.name)}</option>`).join("");["#employee_select","#pay_employee_select"].forEach(id=>{const el=$(id);if(el){el.innerHTML=html;el.value=employee()?.id||""}})}
function showView(name){currentView=name;document.querySelectorAll("[data-admin-view]").forEach(el=>el.hidden=el.dataset.adminView!==name);document.querySelectorAll(".navTab").forEach(b=>b.classList.toggle("active",b.dataset.view===name));window.scrollTo({top:0,behavior:"smooth"})}
function chooseEmployee(id,view){if(!D.employees.some(e=>e.id===id))return;selectedEmployeeId=id;render();defaults(employee().pay_frequency,true);if(view)showView(view)}
function setup(){login()}function login(){const s=$("#setup");if(s)s.hidden=true;$("#login").hidden=false;$("#app").hidden=true}function app(){const s=$("#setup");if(s)s.hidden=true;$("#login").hidden=true;$("#app").hidden=false}
function completedWeek(){const t=new Date();t.setHours(12,0,0,0);const end=new Date(t);end.setDate(t.getDate()-(t.getDay()||7));const start=new Date(end);start.setDate(end.getDate()-6);return{start:date(start),end:date(end)}}
function defaults(freq,force=false){if(!force&&$("#period_start").value)return;const w=completedWeek(),z=new Date(w.end+"T12:00:00");const a=new Date(z);a.setDate(z.getDate()-(freq==="biweekly"?13:6));set("#period_start",date(a));set("#period_end",w.end);set("#payment_date",date(new Date()))}
function taxState(){const f=$("#w4_on_file").checked,h=$("#hw4_on_file").checked;["#federal_filing_status","#w4_step2_checked","#w4_step3_credits","#w4_step4a_other_income","#w4_step4b_deductions","#w4_step4c_extra","#w4_exempt","#w4_nonresident_alien","#w4_nra_india_exception"].forEach(x=>$(x).disabled=!f);["#hi_filing_status","#hi_allowances","#hi_additional_withholding"].forEach(x=>$(x).disabled=!h)}
function entryCovered(t){return D.runs.some(r=>r.employee_id===t.employee_id&&t.business_date>=r.period_start&&t.business_date<=r.period_end)}
function renderOverview(){const active=D.employees.filter(e=>e.status!=="Inactive"),w=completedWeek(),weekEntries=D.entries.filter(t=>t.business_date>=w.start&&t.business_date<=w.end),hours=weekEntries.reduce((s,t)=>s+(+t.regular_hours||0)+(+t.overtime_hours||0),0),awaiting=active.filter(e=>weekEntries.some(t=>t.employee_id===e.id&&!entryCovered(t))),last=[...D.runs].sort((a,b)=>String(b.payment_date).localeCompare(String(a.payment_date)))[0];
$("#overviewEmployeeCount").textContent=active.length;$("#overviewHours").textContent=num(hours);$("#overviewAwaiting").textContent=awaiting.length;$("#overviewLastPayroll").textContent=last?last.payment_date:"—";$("#overviewPeriodLabel").textContent=`Completed pay week: ${w.start} – ${w.end}`;
const cards=active.map(e=>{const es=weekEntries.filter(t=>t.employee_id===e.id),eh=es.reduce((s,t)=>s+(+t.regular_hours||0)+(+t.overtime_hours||0),0),gross=es.reduce((s,t)=>s+(+t.regular_hours||0)*(+t.hourly_wage||+e.hourly_rate)+(+(t.overtime_hours)||0)*(+t.hourly_wage||+e.hourly_rate)*1.5,0),unpaid=es.some(t=>!entryCovered(t)),status=!+e.hourly_rate?"Needs hourly rate":!eh?"No hours this week":unpaid?"Ready for payroll":"Payroll recorded";return `<article class="employeeCard"><div><p class="eyebrow">${esc(status)}</p><h3>${esc(e.name)}</h3><p>${money(e.hourly_rate)}/hr · ${num(eh)} hrs · ${money(gross)} gross</p></div><div class="actions"><button class="small secondary" data-open-employee="${esc(e.id)}">Employee</button><button class="small" data-run-payroll="${esc(e.id)}" ${eh?"":"disabled"}>Payroll</button></div></article>`}).join("");
$("#overviewEmployees").innerHTML=cards||'<p class="note">No active employees yet.</p>';
const totalGross=weekEntries.reduce((s,t)=>s+(+t.regular_hours||0)*(+t.hourly_wage||0)+(+t.overtime_hours||0)*(+t.hourly_wage||0)*1.5,0);
$("#overviewPayrollSummary").innerHTML=`<b>${awaiting.length} employee${awaiting.length===1?"":"s"} awaiting payroll</b><span>${num(hours)} hours · ${money(totalGross)} gross in completed week</span><span>${w.start} – ${w.end}</span>`;
const latest=[...D.entries].sort((a,b)=>String(b.synced_at||b.business_date).localeCompare(String(a.synced_at||a.business_date)))[0];
$("#overviewImportSummary").innerHTML=`<b>${D.entries.length} stored time entries</b><span>${latest?"Latest: "+esc(latest.business_date)+" · "+esc(employeeName(latest.employee_id)):"No time imported yet"}</span><span>Toast CSV preview protects against accidental imports.</span>`}
function render(){const e=employee();if(!e)return;selectedEmployeeId=e.id;employeeOptions();$("#employeeHeading").textContent=e.name;["hourly_rate","pay_frequency","toast_employee_guid","federal_filing_status","w4_step3_credits","w4_step4a_other_income","w4_step4b_deductions","w4_step4c_extra","hi_filing_status","hi_allowances","hi_additional_withholding"].forEach(k=>set("#"+k,e[k]));["w4_on_file","w4_step2_checked","w4_exempt","w4_nonresident_alien","w4_nra_india_exception","hw4_on_file"].forEach(k=>check("#"+k,e[k]));defaults(e.pay_frequency);
const runs=D.runs.filter(r=>r.employee_id===e.id);
$("#runsBody").innerHTML=runs.map(r=>{const ded=+r.social_security+ +r.medicare+ +(r.additional_medicare||0)+ +r.federal_income_tax+ +r.hawaii_income_tax+ +r.other_deductions;return `<tr><td>${esc(r.payment_date)}</td><td>${esc(r.period_start)}–${esc(r.period_end)}</td><td>${esc(r.pay_frequency)}</td><td>${num(+r.regular_hours+ +r.overtime_hours)}</td><td>${money(r.gross_pay)}</td><td>${money(ded)}</td><td><b>${money(r.net_pay)}</b></td><td><b>${money(r.amount_paid)}</b></td><td>${esc(r.payment_method)}</td><td>${r.apply_tax_deductions?"Applied":"OFF"}</td></tr>`}).join("")||'<tr><td colspan="10">No payments recorded for this employee.</td></tr>';
$("#entriesBody").innerHTML=D.entries.map(t=>`<tr><td><b>${esc(employeeName(t.employee_id))}</b></td><td>${esc(t.business_date)}</td><td>${num(t.regular_hours)}</td><td>${num(t.overtime_hours)}</td><td>${money(t.hourly_wage)}</td><td>${money(+t.regular_hours*+t.hourly_wage+ +t.overtime_hours*+t.hourly_wage*1.5)}</td><td>${esc(t.source)}</td><td><button class="small secondary" data-a="edit" data-g="${esc(t.toast_guid)}">Edit</button> <button class="small danger" data-a="delete" data-g="${esc(t.toast_guid)}">Delete</button></td></tr>`).join("")||'<tr><td colspan="8">No time entries yet.</td></tr>';
$("#auditBody").innerHTML=(D.audit||[]).map(a=>{const b=a.before_data||{},n=a.after_data||{},x=n.employee_id||b.employee_id,d=n.business_date||b.business_date||"—";return `<tr><td><b>${esc(employeeName(x))}</b></td><td>${new Date(a.created_at).toLocaleString()}</td><td>${esc(a.action)}</td><td>${esc(d)}</td><td>${a.action==="delete"?"Deleted entry":`Changed ${num(b.regular_hours)} regular/${num(b.overtime_hours)} OT → ${num(n.regular_hours)} regular/${num(n.overtime_hours)} OT`}</td></tr>`}).join("")||'<tr><td colspan="5">No corrections recorded.</td></tr>';
const w=completedWeek(),ee=D.entries.filter(t=>t.employee_id===e.id&&t.business_date>=w.start&&t.business_date<=w.end),eh=ee.reduce((s,t)=>s+(+t.regular_hours||0)+(+t.overtime_hours||0),0),unpaid=ee.some(t=>!entryCovered(t));$("#payrollEmployeeStatus").innerHTML=`<b>${esc(e.name)}</b><span>${money(e.hourly_rate)}/hr · ${num(eh)} hours in completed week</span><span>${unpaid?"Ready for payroll":eh?"Completed-week hours already covered by a payroll run":"No completed-week hours yet"}</span>`;
renderOverview();taxState();previewSoon();showView(currentView)}
async function load(){D=await api("data");if(!D.employees.some(e=>e.id===selectedEmployeeId))selectedEmployeeId=D.employees[0]?.id||"";render()}
function emp(){const e=employee(),o={id:e.id};["hourly_rate","pay_frequency","toast_employee_guid","federal_filing_status","w4_step3_credits","w4_step4a_other_income","w4_step4b_deductions","w4_step4c_extra","hi_filing_status","hi_allowances","hi_additional_withholding"].forEach(k=>o[k]=$("#"+k).value);["w4_on_file","w4_step2_checked","w4_exempt","w4_nonresident_alien","w4_nra_india_exception","hw4_on_file"].forEach(k=>o[k]=$("#"+k).checked);return o}
const pay=()=>({employee_id:employee().id,period_start:$("#period_start").value,period_end:$("#period_end").value,payment_date:$("#payment_date").value,apply_tax_deductions:$("#apply_tax_deductions").checked,other_deductions:$("#other_deductions").value,amount_paid:$("#amount_paid").value,payment_method:$("#payment_method").value,payment_reference:$("#payment_reference").value,notes:$("#notes").value});
async function preview(){if(!employee()||!$("#period_start").value)return;try{const r=await api("pay-preview",{method:"POST",body:JSON.stringify(pay())});$("#pvHours").textContent=num(+r.regular_hours+ +r.overtime_hours);$("#pvGross").textContent=money(r.gross_pay);$("#pvFederal").textContent=money(r.federal_income_tax);$("#pvHawaii").textContent=money(r.hawaii_income_tax);$("#pvFica").textContent=money(+r.social_security+ +r.medicare+ +(r.additional_medicare||0));$("#pvNet").textContent=money(r.net_pay)}catch{}}function previewSoon(){clearTimeout(timer);timer=setTimeout(preview,200)}
function status(msg,type="success"){const e=$("#importStatus");e.hidden=false;e.className="status "+type;e.textContent=msg}
const setupForm=$("#setupForm");if(setupForm)setupForm.onsubmit=async e=>{e.preventDefault();login()};
$("#loginForm").onsubmit=async e=>{e.preventDefault();const b=$("#loginSubmit");$("#loginMsg").className="status working";$("#loginMsg").textContent="Signing in…";b.disabled=true;b.classList.add("is-loading");b.textContent="Signing in…";try{await api("login",{method:"POST",body:JSON.stringify({email:$("#email").value,password:$("#password").value})});$("#loginMsg").className="status working";$("#loginMsg").textContent="Password accepted. Establishing secure session…";await new Promise(r=>setTimeout(r,150));try{await api("me");$("#loginMsg").className="ok";$("#loginMsg").textContent="Signed in.";currentView="overview";app();await load()}catch(s){login();$("#loginMsg").className="error";$("#loginMsg").textContent="Password accepted, but the secure session did not persist. Please send a screenshot of this message."}}catch(x){$("#loginMsg").className="error";$("#loginMsg").textContent=x.message||"Sign-in failed."}finally{b.disabled=false;b.classList.remove("is-loading");b.textContent="Sign in"}};$("#showRecovery").onclick=()=>{$("#recoveryPanel").hidden=!$("#recoveryPanel").hidden};
$("#recoveryForm").onsubmit=async e=>{e.preventDefault();$("#recoveryMsg").className="error";$("#recoveryMsg").textContent="";if($("#recovery_password").value!==$("#recovery_confirm").value){$("#recoveryMsg").textContent="Passwords do not match.";return}try{const r=await api("admin-recovery",{method:"POST",body:JSON.stringify({email:$("#recovery_email").value,recovery_key:$("#recovery_key").value,new_password:$("#recovery_password").value})});$("#recoveryMsg").className="ok";$("#recoveryMsg").textContent=r.message||"Password reset complete.";$("#email").value=$("#recovery_email").value;$("#password").value="";$("#recovery_password").value=$("#recovery_confirm").value=$("#recovery_key").value="";}catch(x){$("#recoveryMsg").textContent=x.message}};$("#logout").onclick=async()=>{await api("logout",{method:"POST"}).catch(()=>{});login()};
document.querySelectorAll(".navTab").forEach(b=>b.onclick=()=>showView(b.dataset.view));
$("#dashboardImportBtn").onclick=()=>$("#csvFile").click();
$("#overviewImportBtn").onclick=()=>$("#csvFile").click();
$("#importsImportBtn").onclick=()=>$("#csvFile").click();
$("#dashboardPayrollBtn").onclick=()=>showView("payroll");
$("#overviewPayrollBtn").onclick=()=>showView("payroll");
$("#overviewEmployeesBtn").onclick=()=>showView("employees");
$("#overviewTimeBtn").onclick=()=>showView("time");
$("#overviewEmployees").onclick=e=>{const a=e.target.closest("[data-open-employee]"),p=e.target.closest("[data-run-payroll]");if(a)chooseEmployee(a.dataset.openEmployee,"employees");if(p)chooseEmployee(p.dataset.runPayroll,"payroll")};
$("#employee_select").onchange=e=>chooseEmployee(e.target.value);$("#pay_employee_select").onchange=e=>chooseEmployee(e.target.value);
$("#employeeForm").onsubmit=async e=>{e.preventDefault();await api("employee",{method:"POST",body:JSON.stringify({employee:emp()})});$("#employeeSaved").textContent="Saved.";await load()};$("#pay_frequency").onchange=()=>defaults($("#pay_frequency").value,true);["#w4_on_file","#hw4_on_file"].forEach(x=>$(x).onchange=()=>{taxState();previewSoon()});["#period_start","#period_end","#payment_date","#other_deductions","#apply_tax_deductions"].forEach(x=>$(x).oninput=previewSoon);
$("#payForm").onsubmit=async e=>{e.preventDefault();const r=await api("pay-create",{method:"POST",body:JSON.stringify(pay())});$("#payResult").textContent="Recorded "+money(r.amount_paid)+" paid via "+r.payment_method;$("#amount_paid").value="";await load()};
$("#syncBtn").onclick=async()=>{const z=new Date(),a=new Date(z);a.setDate(a.getDate()-29);try{status("Syncing Toast…","working");const r=await api("toast-sync",{method:"POST",body:JSON.stringify({start:date(a),end:date(z)})});status("Toast sync complete: "+r.imported+" imported, "+r.skipped+" skipped.");await load()}catch(x){status(x.message,"error")}};
$("#passwordForm").onsubmit=async e=>{e.preventDefault();try{await api("change-password",{method:"POST",body:JSON.stringify({current_password:$("#current_password").value,new_password:$("#new_password").value})});$("#passwordMsg").textContent="Password changed.";$("#current_password").value=$("#new_password").value=""}catch(x){$("#passwordMsg").textContent=x.message}};
function parse(text){const rows=[];let r=[],f="",q=false;for(let i=0;i<text.length;i++){const c=text[i];if(q){if(c==='"'){if(text[i+1]==='"'){f+='"';i++}else q=false}else f+=c}else if(c==='"')q=true;else if(c===","){r.push(f);f=""}else if(c==="\n"){r.push(f.replace(/\r$/,""));if(r.some(x=>x.trim()))rows.push(r);r=[];f=""}else f+=c}r.push(f);if(r.some(x=>x.trim()))rows.push(r);return rows}
const key=s=>s.toLowerCase().replace(/^\ufeff/,"").replace(/[^a-z0-9]/g,""),aliases={
name:["employeename","employee","name"],
date:["businessdate","date","shiftdate","workdate"],
reg:["regularhours","reghours","regular"],
ot:["overtimehours","othours","overtime"],
payable:["payablehours","payablehrs"],
total:["totalhours","hours","workedhours"],
rate:["hourlywage","hourlyrate","payrate","wage","rate"],
guid:["timeentryguid","toastguid","timeentryid"],
tin:["timein","clockin","clockintime","indate"],
tout:["timeout","clockout","clockouttime","outdate"],
unpaid:["unpaidbreaktime","unpaidbreak"],
paid:["paidbreaktime","paidbreak"],
tips:["cashtipsdeclared","declaredcashtips"]
},first=(o,a)=>a.map(k=>o[k]).find(v=>String(v||"").trim())||"",n=v=>+String(v||"0").replace(/[$,%\s]/g,"")||0;
const MONTHS={jan:"01",feb:"02",mar:"03",apr:"04",may:"05",jun:"06",jul:"07",aug:"08",sep:"09",oct:"10",nov:"11",dec:"12"};
function iso(v){v=String(v||"").trim();if(/^\d{8}$/.test(v))return v.slice(0,4)+"-"+v.slice(4,6)+"-"+v.slice(6,8);if(/^\d{4}-\d{2}-\d{2}$/.test(v))return v;let m=/^(\d{1,2})-([A-Za-z]{3})-(\d{2}|\d{4})$/.exec(v);if(m){let y=+m[3];if(y<100)y+=2000;const mo=MONTHS[m[2].toLowerCase()];if(mo)return String(y).padStart(4,"0")+"-"+mo+"-"+String(+m[1]).padStart(2,"0")}m=/^([A-Za-z]{3})\s+(\d{1,2}),\s*(\d{4})$/.exec(v);if(m){const mo=MONTHS[m[1].toLowerCase()];if(mo)return m[3]+"-"+mo+"-"+String(+m[2]).padStart(2,"0")}const d=new Date(v);return Number.isNaN(d.getTime())?"":date(d)}
function clock(v){const m=/^(\d{1,2}):(\d{2})\s*(AM|PM)$/i.exec(String(v||"").trim());if(!m)return null;let h=+m[1]%12;if(m[3].toUpperCase()==="PM")h+=12;return h*60+(+m[2])}
function addDaysIso(d,days){const z=new Date(d+"T12:00:00Z");z.setUTCDate(z.getUTCDate()+days);return z.toISOString().slice(0,10)}
function stamp(d,v,next=false){const mins=clock(v);if(!d||mins==null)return null;const dd=next?addDaysIso(d,1):d,hh=String(Math.floor(mins/60)).padStart(2,"0"),mm=String(mins%60).padStart(2,"0");return dd+"T"+hh+":"+mm+":00-10:00"}
function weekMonday(d){const z=new Date(d+"T12:00:00Z"),delta=(z.getUTCDay()+6)%7;z.setUTCDate(z.getUTCDate()-delta);return z.toISOString().slice(0,10)}
function nameParts(v){v=String(v||"").trim();if(v.includes(",")){const a=v.split(","),last=(a.shift()||"").trim(),first=a.join(" ").trim();return{first,last}}const p=v.split(/\s+/).filter(Boolean);return{first:p.slice(0,-1).join(" "),last:p.at(-1)||""}}
const cleanName=v=>String(v||"").toLowerCase().replace(/[^a-z0-9]/g,""),toastDisplayName=v=>{const p=nameParts(v);return [p.first,p.last].filter(Boolean).join(" ")||String(v||"").trim()};
function findEmployeeForToast(nm){if(!nm)return employee();const target=cleanName(nm),parts=nameParts(nm),active=D.employees.filter(e=>e.status!=="Inactive");let m=active.find(e=>(e.toast_aliases||[]).some(a=>cleanName(a)===target));if(m)return m;m=active.find(e=>cleanName(e.name)===target);if(m)return m;const last=cleanName(parts.last),sameLast=active.filter(e=>cleanName(nameParts(e.name).last)===last);return sameLast.length===1?sameLast[0]:null}
function allocateWeeklyOt(rows){const groups={};for(const r of rows){if(!r.valid||r.overtime_mode!=="weekly-derived"||!r.business_date)continue;const who=r.employee_id||"new:"+cleanName(r.toast_employee_name);(groups[who+"|"+weekMonday(r.business_date)]||=[]).push(r)}for(const arr of Object.values(groups)){arr.sort((a,b)=>a.business_date.localeCompare(b.business_date)||String(a.in_date||"").localeCompare(String(b.in_date||"")));let used=0;for(const r of arr){const total=Math.max(0,+r.total_hours||0),reg=Math.min(total,Math.max(0,40-used));r.regular_hours=Math.round(reg*100)/100;r.overtime_hours=Math.round((total-reg)*100)/100;used+=total}}}
function validateCsvRow(r){const worked=Math.max(0,+r.total_hours||(+r.regular_hours||0)+(+r.overtime_hours||0));r.valid=!!(r.business_date&&worked>0&&+r.hourly_wage>0);r.error=r.valid?"":!r.business_date?"Invalid Toast date.":worked<=0?"No payable hours.":+r.hourly_wage<=0?(r.new_employee?"New employee detected — enter hourly rate.":"No hourly wage."):"Check this row."}
async function csv(file){const t=parse(await file.text());if(!t.length)throw Error("CSV is empty.");const hs=t.shift().map(key),out=[],hasReg=aliases.reg.some(h=>hs.includes(h)),hasOt=aliases.ot.some(h=>hs.includes(h)),deriveOt=!hasReg&&!hasOt;for(let i=0;i<t.length;i++){const o=Object.fromEntries(hs.map((h,j)=>[h,t[i][j]||""])),nm=first(o,aliases.name),match=findEmployeeForToast(nm),d=iso(first(o,aliases.date)),payable=Math.max(0,n(first(o,aliases.payable))),reportedTotal=Math.max(0,n(first(o,aliases.total))),total=Math.max(0,payable||reportedTotal),ot=hasOt?Math.max(0,n(first(o,aliases.ot))):0,reg=hasReg?Math.max(0,n(first(o,aliases.reg))):Math.max(0,total-ot),w=Math.max(0,n(first(o,aliases.rate))||+match?.hourly_rate||0),tin=first(o,aliases.tin),tout=first(o,aliases.tout),im=clock(tin),om=clock(tout),row={row_number:i+2,employee_id:match?.id||null,employee_name:match?.name||toastDisplayName(nm),toast_employee_name:nm||match?.name||"",new_employee:!match,business_date:d,regular_hours:deriveOt?total:reg,overtime_hours:deriveOt?0:ot,total_hours:deriveOt?total:reg+ot,hourly_wage:w,in_date:stamp(d,tin),out_date:stamp(d,tout,im!=null&&om!=null&&om<=im),provided_guid:first(o,aliases.guid),overtime_mode:deriveOt?"weekly-derived":"toast-explicit",raw:o};validateCsvRow(row);out.push(row)}allocateWeeklyOt(out);return out}
function csvView(rows,name){const v=rows.filter(x=>x.valid),bad=rows.length-v.length,derived=rows.some(x=>x.overtime_mode==="weekly-derived"),newNames=[...new Set(rows.filter(x=>x.new_employee&&(+x.total_hours||0)>0).map(x=>x.toast_employee_name))];$("#csvPreviewFile").textContent=name+" · "+rows.length+" rows"+(derived?" · OT derived from Payable Hours by Monday–Sunday week":"");const box=$("#csvNewEmployees");box.hidden=!newNames.length;box.innerHTML=newNames.length?'<h3>New employees detected</h3><p class="note">Toast does not include hourly wage in this export. Enter a rate before approving import. A separate payroll employee will be created.</p>'+newNames.map(nm=>{const r=rows.find(x=>x.toast_employee_name===nm),rate=+r?.hourly_wage||"";return `<label>${esc(toastDisplayName(nm))}<small>Toast: ${esc(nm)}</small><input type="number" min=".01" step=".01" data-toast-rate="${esc(nm)}" value="${rate}" placeholder="Hourly rate"></label>`}).join(""):"";$("#csvSummary").innerHTML=`<div><small>Valid</small><b>${v.length}</b></div><div><small>Issues</small><b>${bad}</b></div><div><small>Hours</small><b>${num(v.reduce((s,x)=>s+x.regular_hours+x.overtime_hours,0))}</b></div><div><small>Gross</small><b>${money(v.reduce((s,x)=>s+x.regular_hours*x.hourly_wage+x.overtime_hours*x.hourly_wage*1.5,0))}</b></div>`;$("#csvPreviewBody").innerHTML=rows.map(x=>{const mapped=x.toast_employee_name&&x.toast_employee_name!==x.employee_name?`<small class="csvMap">Toast: ${esc(x.toast_employee_name)} → ${esc(x.employee_name)}</small>`:"",state=x.valid?(x.new_employee?"Ready · new employee":x.overtime_mode==="weekly-derived"?"Ready · weekly OT":"Ready"):esc(x.error);return `<tr class="${x.valid?"":"bad"}"><td>${x.row_number}</td><td>${esc(x.employee_name)}${mapped}</td><td>${esc(x.business_date)}</td><td>${num(x.regular_hours)}</td><td>${num(x.overtime_hours)}</td><td>${x.hourly_wage?money(x.hourly_wage):"—"}</td><td>${state}</td></tr>`}).join("");$("#csvApprove").disabled=!v.length}
$("#csvNewEmployees").onchange=e=>{const input=e.target.closest("[data-toast-rate]");if(!input||!CSV)return;const nm=input.dataset.toastRate,rate=Math.max(0,+input.value||0);for(const r of CSV.filter(x=>x.toast_employee_name===nm)){r.hourly_wage=rate;validateCsvRow(r)}allocateWeeklyOt(CSV);csvView(CSV,CSVNAME)};
$("#csvFile").onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{CSV=await csv(f);CSVNAME=f.name;csvView(CSV,f.name);$("#csvDialog").showModal();status("Preview ready. Nothing imported yet.","working")}catch(x){status(x.message,"error")}};const closeCsv=()=>{$("#csvDialog").close();$("#csvFile").value="";CSV=null};$("#csvCancel").onclick=closeCsv;$("#csvClose").onclick=closeCsv;$("#csvApprove").onclick=async()=>{const r=await api("csv-import",{method:"POST",body:JSON.stringify({file:CSVNAME,rows:CSV.filter(x=>x.valid)})});const made=(r.created_employees||[]).map(e=>e.name);status("CSV import complete: "+r.imported+" imported/updated, "+r.skipped+" skipped."+(made.length?" Created employee"+(made.length>1?"s":"")+": "+made.join(", ")+".":""));closeCsv();await load();showView("overview");if(made.length){const created=D.employees.find(e=>e.name===made[0]);if(created)selectedEmployeeId=created.id;renderOverview()}};
function edit(t){set("#edit_guid",t.toast_guid);set("#edit_business_date",t.business_date);set("#edit_regular_hours",t.regular_hours);set("#edit_overtime_hours",t.overtime_hours);set("#edit_hourly_wage",t.hourly_wage);$("#editDialog").showModal()}const editBody=c=>({toast_guid:$("#edit_guid").value,business_date:$("#edit_business_date").value,regular_hours:$("#edit_regular_hours").value,overtime_hours:$("#edit_overtime_hours").value,hourly_wage:$("#edit_hourly_wage").value,confirm_paid_period:c});
$("#editForm").onsubmit=async e=>{e.preventDefault();try{await api("time-update",{method:"POST",body:JSON.stringify(editBody(false))})}catch(x){if(!x.requires_confirmation||!confirm("This shift is in a recorded payroll period. Historical payroll will remain unchanged. Continue?"))return;await api("time-update",{method:"POST",body:JSON.stringify(editBody(true))})}$("#editDialog").close();await load()};$("#editCancel").onclick=()=>$("#editDialog").close();$("#entriesBody").onclick=async e=>{const b=e.target.closest("button[data-a]");if(!b)return;const t=D.entries.find(x=>x.toast_guid===b.dataset.g);if(b.dataset.a==="edit")return edit(t);if(!confirm("Delete this time entry? An audit record will remain."))return;try{await api("time-delete",{method:"POST",body:JSON.stringify({toast_guid:t.toast_guid})})}catch(x){if(!x.requires_confirmation||!confirm("This shift is in a recorded payroll period. Historical payroll will remain unchanged. Delete anyway?"))return;await api("time-delete",{method:"POST",body:JSON.stringify({toast_guid:t.toast_guid,confirm_paid_period:true})})}await load()};
(async()=>{try{await api("me");app();await load()}catch{login()}})();