const BUILD="20261006-6";
const $=s=>document.querySelector(s),money=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(+n||0),num=n=>(+n||0).toFixed(2),esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const ep=o=>"/.netlify/functions/payroll-admin?op="+encodeURIComponent(o);let D={employees:[],entries:[],runs:[],audit:[]},timer,CSV=null,CSVNAME="";
async function api(op,opt={}){const h={...(opt.headers||{})};if(opt.body)h["content-type"]="application/json";const url=ep(op)+(op==="status"||op==="me"?"&t="+Date.now():"");const r=await fetch(url,{credentials:"same-origin",cache:"no-store",...opt,headers:h}),j=await r.json().catch(()=>({error:"Request failed."}));if(r.status===401&&!["login","setup","status"].includes(op))login();if(!r.ok){const e=Error(j.error||"Request failed.");Object.assign(e,j);throw e}return j}
const employee=()=>D.employees.find(e=>e.id==="craig-wong")||D.employees[0],set=(id,v)=>{$(id).value=v??""},check=(id,v)=>{$(id).checked=!!v},date=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);
function setup(){login()}function login(){const s=$("#setup");if(s)s.hidden=true;$("#login").hidden=false;$("#app").hidden=true}function app(){const s=$("#setup");if(s)s.hidden=true;$("#login").hidden=true;$("#app").hidden=false}
function defaults(freq,force=false){if(!force&&$("#period_start").value)return;const t=new Date();t.setHours(12,0,0,0);const z=new Date(t);z.setDate(t.getDate()-(t.getDay()||7));const a=new Date(z);a.setDate(z.getDate()-(freq==="biweekly"?13:6));set("#period_start",date(a));set("#period_end",date(z));set("#payment_date",date(t))}
function taxState(){const f=$("#w4_on_file").checked,h=$("#hw4_on_file").checked;["#federal_filing_status","#w4_step2_checked","#w4_step3_credits","#w4_step4a_other_income","#w4_step4b_deductions","#w4_step4c_extra","#w4_exempt","#w4_nonresident_alien","#w4_nra_india_exception"].forEach(x=>$(x).disabled=!f);["#hi_filing_status","#hi_allowances","#hi_additional_withholding"].forEach(x=>$(x).disabled=!h)}
function render(){const e=employee();if(e){$("#rateCard").textContent=money(e.hourly_rate)+"/hr";["hourly_rate","pay_frequency","toast_employee_guid","federal_filing_status","w4_step3_credits","w4_step4a_other_income","w4_step4b_deductions","w4_step4c_extra","hi_filing_status","hi_allowances","hi_additional_withholding"].forEach(k=>set("#"+k,e[k]));["w4_on_file","w4_step2_checked","w4_exempt","w4_nonresident_alien","w4_nra_india_exception","hw4_on_file"].forEach(k=>check("#"+k,e[k]));defaults(e.pay_frequency)}$("#entryCount").textContent=D.entries.length;$("#lastPayment").textContent=D.runs[0]?money(D.runs[0].amount_paid)+" · "+D.runs[0].payment_date:"—";
$("#runsBody").innerHTML=D.runs.map(r=>{const ded=+r.social_security+ +r.medicare+ +(r.additional_medicare||0)+ +r.federal_income_tax+ +r.hawaii_income_tax+ +r.other_deductions;return `<tr><td>${esc(r.payment_date)}</td><td>${esc(r.period_start)}–${esc(r.period_end)}</td><td>${esc(r.pay_frequency)}</td><td>${num(+r.regular_hours+ +r.overtime_hours)}</td><td>${money(r.gross_pay)}</td><td>${money(ded)}</td><td><b>${money(r.net_pay)}</b></td><td><b>${money(r.amount_paid)}</b></td><td>${esc(r.payment_method)}</td><td>${r.apply_tax_deductions?"Applied":"OFF"}</td></tr>`}).join("")||'<tr><td colspan="10">No payments recorded.</td></tr>';
$("#entriesBody").innerHTML=D.entries.map(t=>`<tr><td>${esc(t.business_date)}</td><td>${num(t.regular_hours)}</td><td>${num(t.overtime_hours)}</td><td>${money(t.hourly_wage)}</td><td>${money(+t.regular_hours*+t.hourly_wage+ +t.overtime_hours*+t.hourly_wage*1.5)}</td><td>${esc(t.source)}</td><td><button class="small secondary" data-a="edit" data-g="${esc(t.toast_guid)}">Edit</button> <button class="small danger" data-a="delete" data-g="${esc(t.toast_guid)}">Delete</button></td></tr>`).join("")||'<tr><td colspan="7">No time entries yet.</td></tr>';
$("#auditBody").innerHTML=(D.audit||[]).map(a=>{const b=a.before_data||{},n=a.after_data||{},d=n.business_date||b.business_date||"—";return `<tr><td>${new Date(a.created_at).toLocaleString()}</td><td>${esc(a.action)}</td><td>${esc(d)}</td><td>${a.action==="delete"?"Deleted entry":`Changed ${num(b.regular_hours)} regular/${num(b.overtime_hours)} OT → ${num(n.regular_hours)} regular/${num(n.overtime_hours)} OT`}</td></tr>`}).join("")||'<tr><td colspan="4">No corrections recorded.</td></tr>';taxState();previewSoon()}
async function load(){D=await api("data");render()}
function emp(){const e=employee(),o={id:e.id};["hourly_rate","pay_frequency","toast_employee_guid","federal_filing_status","w4_step3_credits","w4_step4a_other_income","w4_step4b_deductions","w4_step4c_extra","hi_filing_status","hi_allowances","hi_additional_withholding"].forEach(k=>o[k]=$("#"+k).value);["w4_on_file","w4_step2_checked","w4_exempt","w4_nonresident_alien","w4_nra_india_exception","hw4_on_file"].forEach(k=>o[k]=$("#"+k).checked);return o}
const pay=()=>({employee_id:employee().id,period_start:$("#period_start").value,period_end:$("#period_end").value,payment_date:$("#payment_date").value,apply_tax_deductions:$("#apply_tax_deductions").checked,other_deductions:$("#other_deductions").value,amount_paid:$("#amount_paid").value,payment_method:$("#payment_method").value,payment_reference:$("#payment_reference").value,notes:$("#notes").value});
async function preview(){if(!employee()||!$("#period_start").value)return;try{const r=await api("pay-preview",{method:"POST",body:JSON.stringify(pay())});$("#pvHours").textContent=num(+r.regular_hours+ +r.overtime_hours);$("#pvGross").textContent=money(r.gross_pay);$("#pvFederal").textContent=money(r.federal_income_tax);$("#pvHawaii").textContent=money(r.hawaii_income_tax);$("#pvFica").textContent=money(+r.social_security+ +r.medicare+ +(r.additional_medicare||0));$("#pvNet").textContent=money(r.net_pay)}catch{}}function previewSoon(){clearTimeout(timer);timer=setTimeout(preview,200)}
function status(msg,type="success"){const e=$("#importStatus");e.hidden=false;e.className="status "+type;e.textContent=msg}
const setupForm=$("#setupForm");if(setupForm)setupForm.onsubmit=async e=>{e.preventDefault();login()};
$("#loginForm").onsubmit=async e=>{e.preventDefault();try{await api("login",{method:"POST",body:JSON.stringify({email:$("#email").value,password:$("#password").value})});app();await load()}catch(x){$("#loginMsg").textContent=x.message}};$("#showRecovery").onclick=()=>{$("#recoveryPanel").hidden=!$("#recoveryPanel").hidden};
$("#recoveryForm").onsubmit=async e=>{e.preventDefault();$("#recoveryMsg").className="error";$("#recoveryMsg").textContent="";if($("#recovery_password").value!==$("#recovery_confirm").value){$("#recoveryMsg").textContent="Passwords do not match.";return}try{const r=await api("admin-recovery",{method:"POST",body:JSON.stringify({email:$("#recovery_email").value,recovery_key:$("#recovery_key").value,new_password:$("#recovery_password").value})});$("#recoveryMsg").className="ok";$("#recoveryMsg").textContent=r.message||"Password reset complete.";$("#email").value=$("#recovery_email").value;$("#password").value="";$("#recovery_password").value=$("#recovery_confirm").value=$("#recovery_key").value="";}catch(x){$("#recoveryMsg").textContent=x.message}};$("#logout").onclick=async()=>{await api("logout",{method:"POST"}).catch(()=>{});login()};
$("#employeeForm").onsubmit=async e=>{e.preventDefault();await api("employee",{method:"POST",body:JSON.stringify({employee:emp()})});$("#employeeSaved").textContent="Saved.";await load()};$("#pay_frequency").onchange=()=>defaults($("#pay_frequency").value,true);["#w4_on_file","#hw4_on_file"].forEach(x=>$(x).onchange=()=>{taxState();previewSoon()});["#period_start","#period_end","#payment_date","#other_deductions","#apply_tax_deductions"].forEach(x=>$(x).oninput=previewSoon);
$("#payForm").onsubmit=async e=>{e.preventDefault();const r=await api("pay-create",{method:"POST",body:JSON.stringify(pay())});$("#payResult").textContent="Recorded "+money(r.amount_paid)+" paid via "+r.payment_method;$("#amount_paid").value="";await load()};
$("#syncBtn").onclick=async()=>{const z=new Date(),a=new Date(z);a.setDate(a.getDate()-29);try{status("Syncing Toast…","working");const r=await api("toast-sync",{method:"POST",body:JSON.stringify({start:date(a),end:date(z)})});status("Toast sync complete: "+r.imported+" imported, "+r.skipped+" skipped.");await load()}catch(x){status(x.message,"error")}};
$("#passwordForm").onsubmit=async e=>{e.preventDefault();try{await api("change-password",{method:"POST",body:JSON.stringify({current_password:$("#current_password").value,new_password:$("#new_password").value})});$("#passwordMsg").textContent="Password changed.";$("#current_password").value=$("#new_password").value=""}catch(x){$("#passwordMsg").textContent=x.message}};
function parse(text){const rows=[];let r=[],f="",q=false;for(let i=0;i<text.length;i++){const c=text[i];if(q){if(c==='"'){if(text[i+1]==='"'){f+='"';i++}else q=false}else f+=c}else if(c==='"')q=true;else if(c===","){r.push(f);f=""}else if(c==="\n"){r.push(f.replace(/\r$/,""));if(r.some(x=>x.trim()))rows.push(r);r=[];f=""}else f+=c}r.push(f);if(r.some(x=>x.trim()))rows.push(r);return rows}
const key=s=>s.toLowerCase().replace(/^\ufeff/,"").replace(/[^a-z0-9]/g,""),aliases={name:["employeename","employee","name"],date:["businessdate","date","shiftdate","workdate"],reg:["regularhours","reghours","regular"],ot:["overtimehours","othours","overtime"],total:["totalhours","hours","workedhours"],rate:["hourlywage","hourlyrate","payrate","wage","rate"],guid:["timeentryguid","toastguid","timeentryid"]},first=(o,a)=>a.map(k=>o[k]).find(v=>String(v||"").trim())||"",n=v=>+String(v||"0").replace(/[$,%\s]/g,"")||0;
function iso(v){v=String(v||"").trim();if(/^\d{8}$/.test(v))return v.slice(0,4)+"-"+v.slice(4,6)+"-"+v.slice(6,8);const d=new Date(v);return Number.isNaN(d.getTime())?"":date(d)}
async function csv(file){const t=parse(await file.text()),hs=t.shift().map(key),e=employee(),out=[];for(let i=0;i<t.length;i++){const o=Object.fromEntries(hs.map((h,j)=>[h,t[i][j]||""])),nm=first(o,aliases.name),d=iso(first(o,aliases.date)),ot=Math.max(0,n(first(o,aliases.ot))),total=Math.max(0,n(first(o,aliases.total))),reg=Math.max(0,n(first(o,aliases.reg))||Math.max(0,total-ot)),w=Math.max(0,n(first(o,aliases.rate))||+e.hourly_rate),ok=(!nm||nm.toLowerCase().replace(",","").includes("craig"))&&d&&(reg||ot)&&w;out.push({row_number:i+2,employee_id:e.id,employee_name:nm||e.name,business_date:d,regular_hours:reg,overtime_hours:ot,hourly_wage:w,provided_guid:first(o,aliases.guid),valid:!!ok,error:ok?"":"Check employee, date, hours or wage."})}return out}
function csvView(rows,name){const v=rows.filter(x=>x.valid),bad=rows.length-v.length;$("#csvPreviewFile").textContent=name+" · "+rows.length+" rows";$("#csvSummary").innerHTML=`<div><small>Valid</small><b>${v.length}</b></div><div><small>Issues</small><b>${bad}</b></div><div><small>Hours</small><b>${num(v.reduce((s,x)=>s+x.regular_hours+x.overtime_hours,0))}</b></div><div><small>Gross</small><b>${money(v.reduce((s,x)=>s+x.regular_hours*x.hourly_wage+x.overtime_hours*x.hourly_wage*1.5,0))}</b></div>`;$("#csvPreviewBody").innerHTML=rows.map(x=>`<tr class="${x.valid?"":"bad"}"><td>${x.row_number}</td><td>${esc(x.employee_name)}</td><td>${esc(x.business_date)}</td><td>${num(x.regular_hours)}</td><td>${num(x.overtime_hours)}</td><td>${money(x.hourly_wage)}</td><td>${x.valid?"Ready":esc(x.error)}</td></tr>`).join("");$("#csvApprove").disabled=!v.length}
$("#csvFile").onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{CSV=await csv(f);CSVNAME=f.name;csvView(CSV,f.name);$("#csvDialog").showModal();status("Preview ready. Nothing imported yet.","working")}catch(x){status(x.message,"error")}};const closeCsv=()=>{$("#csvDialog").close();$("#csvFile").value="";CSV=null};$("#csvCancel").onclick=closeCsv;$("#csvClose").onclick=closeCsv;$("#csvApprove").onclick=async()=>{const r=await api("csv-import",{method:"POST",body:JSON.stringify({file:CSVNAME,rows:CSV.filter(x=>x.valid)})});status("CSV import complete: "+r.imported+" imported/updated, "+r.skipped+" skipped.");closeCsv();await load()};
function edit(t){set("#edit_guid",t.toast_guid);set("#edit_business_date",t.business_date);set("#edit_regular_hours",t.regular_hours);set("#edit_overtime_hours",t.overtime_hours);set("#edit_hourly_wage",t.hourly_wage);$("#editDialog").showModal()}const editBody=c=>({toast_guid:$("#edit_guid").value,business_date:$("#edit_business_date").value,regular_hours:$("#edit_regular_hours").value,overtime_hours:$("#edit_overtime_hours").value,hourly_wage:$("#edit_hourly_wage").value,confirm_paid_period:c});
$("#editForm").onsubmit=async e=>{e.preventDefault();try{await api("time-update",{method:"POST",body:JSON.stringify(editBody(false))})}catch(x){if(!x.requires_confirmation||!confirm("This shift is in a recorded payroll period. Historical payroll will remain unchanged. Continue?"))return;await api("time-update",{method:"POST",body:JSON.stringify(editBody(true))})}$("#editDialog").close();await load()};$("#editCancel").onclick=()=>$("#editDialog").close();$("#entriesBody").onclick=async e=>{const b=e.target.closest("button[data-a]");if(!b)return;const t=D.entries.find(x=>x.toast_guid===b.dataset.g);if(b.dataset.a==="edit")return edit(t);if(!confirm("Delete this time entry? An audit record will remain."))return;try{await api("time-delete",{method:"POST",body:JSON.stringify({toast_guid:t.toast_guid})})}catch(x){if(!x.requires_confirmation||!confirm("This shift is in a recorded payroll period. Historical payroll will remain unchanged. Delete anyway?"))return;await api("time-delete",{method:"POST",body:JSON.stringify({toast_guid:t.toast_guid,confirm_paid_period:true})})}await load()};
(async()=>{try{await api("me");app();await load()}catch{login()}})();